### ISSUE TITLE
Unable to successfully run on rpi3

### ISSUE THREAD

**Issue by axelson** [blue-heron/blue_heron#55]
This might be another incarnation of #38, or at least the failing data appears very similar, but I'm getting this error on commit 6b331ad8d1cd9 which is the current `main`. Here is the sasl report for the error that I see:

```
00:42:26.434 [error] Process #PID<0.2776.0> terminating
** (FunctionClauseError) no function clause matching in BlueHeron.ATT.Client.ready/3
    (blue_heron 0.1.1) lib/blue_heron/att/client.ex:169: BlueHeron.ATT.Client.ready(:info, {:HCI_ACL_DATA_PACKET, %BlueHeron.ACL{data: %BlueHeron.L2Cap{cid: 4, data: %BlueHeron.ATT.ExchangeMTUResponse{opcode: 3, server_rx_mtu: 23}}, flags: %{bc: 0, pb: 0}, handle: 576}}, %BlueHeron.ATT.Client{attributes: [], caller: nil, client_mtu: 1961, connection: nil, connection_timer: nil, controlling_process: #PID<0.2770.0>, create_connection: nil, ctx: #BlueHeron.Context<0.2771.0>, server_mtu: nil, starting_handle: 1})
    (stdlib 3.13) gen_statem.erl:1166: :gen_statem.loop_state_callback/11
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```
<details>
 <summary>Full log</summary>

```
00:42:25.811 [info]  Init commands completed successfully

00:42:25.812 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x13, 0xC>>,
  return_parameters: %{status: 0x0}
}

00:42:25.813 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x13, 0xC>>,
  return_parameters: %{status: 0x0}
}

00:42:25.814 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x13, 0xC>>,
  return_parameters: %{status: 0x0}
}

00:42:26.331 [info]  Starting connection for H6001 Govee Bulb #Address<A4:C1:38:EC:49:BD>

00:42:26.332 [info]  Opening connection: %BlueHeron.HCI.Command.LEController.CreateConnection{connection_interval_max: 24, connection_interval_min: 8, connection_latency: 4, initiator_filter_policy: 0, le_scan_interval: 96, le_scan_window: 48, max_ce_length: 48, min_ce_length: 2, ocf: 13, ogf: 8, opcode: "\r ", own_address_type: 0, peer_address: 181149790652861, peer_address_type: 0, supervision_timeout: 72}

00:42:26.342 [info]  open connection success: {#PID<0.2770.0>, #Reference<0.912690843.805830659.151761>}

00:42:26.345 [info]  Connection established

00:42:26.345 [info]  Govee connection established for H6001 Govee Bulb A4:C1:38:EC:49:BD

00:42:26.420 [info]  Server MTU: 23

00:42:26.434 [error] Process #PID<0.2776.0> terminating
** (FunctionClauseError) no function clause matching in BlueHeron.ATT.Client.ready/3
    (blue_heron 0.1.1) lib/blue_heron/att/client.ex:169: BlueHeron.ATT.Client.ready(:info, {:HCI_ACL_DATA_PACKET, %BlueHeron.ACL{data: %BlueHeron.L2Cap{cid: 4, data: %BlueHeron.ATT.ExchangeMTUResponse{opcode: 3, server_rx_mtu: 23}}, flags: %{bc: 0, pb: 0}, handle: 576}}, %BlueHeron.ATT.Client{attributes: [], caller: nil, client_mtu: 1961, connection: nil, connection_timer: nil, controlling_process: #PID<0.2770.0>, create_connection: nil, ctx: #BlueHeron.Context<0.2771.0>, server_mtu: nil, starting_handle: 1})
    (stdlib 3.13) gen_statem.erl:1166: :gen_statem.loop_state_callback/11
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Initial Call: BlueHeron.ATT.Client.init/1
Ancestors: [BLEServer, GoveePhx.Supervisor, #PID<0.2409.0>]
Message Queue Length: 0
Messages: []
Links: [#PID<0.2770.0>]
Dictionary: []
Trapping Exits: false
Status: :running
Heap Size: 2586
Stack Size: 28
Reductions: 23817
Neighbours:
    #PID<0.2773.0>
        Initial Call: Circuits.UART.init/1
        Current Call: :gen_server.loop/7
        Ancestors: [#PID<0.2772.0>, #PID<0.2771.0>, BLEServer, GoveePhx.Supervisor, #PID<0.2409.0>]
        Message Queue Length: 0
        Links: [#PID<0.2772.0>, #Port<0.93>]
        Trapping Exits: false
        Status: :waiting
        Heap Size: 1598
        Stack Size: 12
        Reductions: 4839
        Current Stacktrace:
            (stdlib 3.13) gen_server.erl:437: :gen_server.loop/7
            (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    #PID<0.2772.0>
        Initial Call: BlueHeronTransportUART.init/1
        Current Call: :gen_server.loop/7
        Ancestors: [#PID<0.2771.0>, BLEServer, GoveePhx.Supervisor, #PID<0.2409.0>]
        Message Queue Length: 0
        Links: [#PID<0.2771.0>, #PID<0.2773.0>]
        Trapping Exits: false
        Status: :waiting
        Heap Size: 610
        Stack Size: 12
        Reductions: 1589
        Current Stacktrace:
            (stdlib 3.13) gen_server.erl:437: :gen_server.loop/7
            (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    #PID<0.2775.0>
        Initial Call: BlueHeron.ATT.Client.init/1
        Current Call: :gen_statem.loop_receive/3
        Ancestors: [BLEServer, GoveePhx.Supervisor, #PID<0.2409.0>]
        Message Queue Length: 0
        Links: [#PID<0.2770.0>]
        Trapping Exits: false
        Status: :waiting
        Heap Size: 2586
        Stack Size: 11
        Reductions: 26346
        Current Stacktrace:
            (stdlib 3.13) gen_statem.erl:1007: :gen_statem.loop_receive/3
            (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    #PID<0.2777.0>
        Initial Call: BlueHeron.ATT.Client.init/1
        Current Call: :erts_internal.await_result/1
        Ancestors: [BLEServer, GoveePhx.Supervisor, #PID<0.2409.0>]
        Message Queue Length: 0
        Links: [#PID<0.2770.0>]
        Trapping Exits: false
        Status: :running
        Heap Size: 1598
        Stack Size: 35
        Reductions: 24876
        Current Stacktrace:
            :erts_internal.await_result/1
            (stdlib 3.13) proc_lib.erl:753: :proc_lib.proc_info/2
            (stdlib 3.13) proc_lib.erl:725: :proc_lib.get_process_info/2
            (stdlib 3.13) proc_lib.erl:659: :proc_lib.make_neighbour_report/1
            (stdlib 3.13) proc_lib.erl:632: :proc_lib.make_neighbour_reports1/1
            (stdlib 3.13) proc_lib.erl:640: :proc_lib.make_neighbour_reports1/1
            (stdlib 3.13) proc_lib.erl:527: :proc_lib.crash_report/4
            (stdlib 3.13) proc_lib.erl:246: :proc_lib.exit_p/3
    #PID<0.2771.0>
        Initial Call: BlueHeron.HCI.Transport.init/1
        Current Call: :gen_statem.loop_receive/3
        Ancestors: [BLEServer, GoveePhx.Supervisor, #PID<0.2409.0>]
        Message Queue Length: 0
        Links: [#PID<0.2770.0>, #PID<0.2772.0>]
        Trapping Exits: false
        Status: :waiting
        Heap Size: 4185
        Stack Size: 11
        Reductions: 96433
        Current Stacktrace:
            (stdlib 3.13) gen_statem.erl:1007: :gen_statem.loop_receive/3
            (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    BLEServer (#PID<0.2770.0>)
        Initial Call: Govee.BLEConnection.init/1
        Current Call: :gen_server.loop/7
        Ancestors: [GoveePhx.Supervisor, #PID<0.2409.0>]
        Message Queue Length: 0
        Links: [#PID<0.2771.0>, #PID<0.2776.0>, #PID<0.2777.0>, #PID<0.2775.0>, #PID<0.2410.0>]
        Trapping Exits: false
        Status: :waiting
        Heap Size: 4185
        Stack Size: 12
        Reductions: 13996
        Current Stacktrace:
            (stdlib 3.13) gen_server.erl:437: :gen_server.loop/7
            (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

00:42:26.446 [error] Child Govee.BLEConnection of Supervisor GoveePhx.Supervisor terminated
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in BlueHeron.ATT.Client.ready/3
        (blue_heron 0.1.1) lib/blue_heron/att/client.ex:169: BlueHeron.ATT.Client.ready(:info, {:HCI_ACL_DATA_PACKET, %BlueHeron.ACL{data: %BlueHeron.L2Cap{cid: 4, data: %BlueHeron.ATT.ExchangeMTUResponse{opcode: 3, server_rx_mtu: 23}}, flags: %{bc: 0, pb: 0}, handle: 576}}, %BlueHeron.ATT.Client{attributes: [], caller: nil, client_mtu: 1961, connection: nil, connection_timer: nil, controlling_process: #PID<0.2770.0>, create_connection: nil, ctx: #BlueHeron.Context<0.2771.0>, server_mtu: nil, starting_handle: 1})
        (stdlib 3.13) gen_statem.erl:1166: :gen_statem.loop_state_callback/11
        (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Pid: #PID<0.2770.0>
Start Call: Govee.BLEConnection.start_link([devices: [[type: :h6001, addr: 181149790652861], [type: :h6001, addr: 181149780509914], [type: :h6159, addr: 181149781888623]], transport_config: %BlueHeronTransportUART{device: "ttyAMA0", init_commands: [%BlueHeron.HCI.Command.ControllerAndBaseband.WriteLocalName{name: "Govee Controller", ocf: 19, ogf: 3, opcode: <<19, 12>>}], recv: nil, uart_opts: [speed: 115200], uart_pid: nil}])
Restart: :permanent
Shutdown: 5000
Type: :worker

00:42:26.447 [error] Child Govee.BLEConnection of Supervisor GoveePhx.Supervisor caused shutdown
** (exit) :reached_max_restart_intensity
Start Call: Govee.BLEConnection.start_link([devices: [[type: :h6001, addr: 181149790652861], [type: :h6001, addr: 181149780509914], [type: :h6159, addr: 181149781888623]], transport_config: %BlueHeronTransportUART{device: "ttyAMA0", init_commands: [%BlueHeron.HCI.Command.ControllerAndBaseband.WriteLocalName{name: "Govee Controller", ocf: 19, ogf: 3, opcode: <<19, 12>>}], recv: nil, uart_opts: [speed: 115200], uart_pid: nil}])
Restart: :permanent
Shutdown: 5000
Type: :worker
```
</details>

**Comment by axelson** [comment]
By adding this clause to `ready` my code is working (but I'm not sure this is a viable fix for the issue):
```
  def ready(:info, {:HCI_ACL_DATA_PACKET, _}, _data), do: :keep_state_and_data
```
