### ISSUE TITLE
SetAdvertisingData ArgumentError

### ISSUE THREAD

**Issue by ConnorRigby** [blue-heron/blue_heron#82]
Serializing `SetAdvertisingData` fails on data lengths longer than a certain threshold. 

```
15:45:54.764 [error] GenStateMachine #PID<0.1465.0> terminating
** (ArgumentError) argument error
    (blue_heron 0.3.0) lib/blue_heron/hci/commands/le_controller/set_advertising_data.ex:11: BlueHeron.HCI.Serializable.BlueHeron.HCI.Command.LEController.SetAdvertisingData.serialize/1
    (blue_heron 0.3.0) lib/blue_heron/hci/transport.ex:209: BlueHeron.HCI.Transport.ready/3
    (stdlib 3.17) gen_statem.erl:1203: :gen_statem.loop_state_callback/11
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
State: {:ready, %BlueHeron.HCI.Transport{calls: %{}, config: %BlueHeronTransportUART{device: "ttyS3", init_commands: [], recv: nil, uart_opts: [speed: 3000000, framing: BlueHeronTransportUART.Framing, active: false, flow_control: :hardware], uart_pid: #PID<0.1464.0>}, errors: 0, handlers: [#PID<0.1467.0>], init_commands: [], max_error_count: 2, monitor: #Reference<0.3143178017.2729181185.138896>, pid: #PID<0.1466.0>}}
Callback mode: :state_functions
Postponed events: []
Last event: {{:call, {#PID<0.1467.0>, [:alias | #Reference<0.3143178017.2729246721.139217>]}}, {:send_command, %BlueHeron.HCI.Command.LEController.SetAdvertisingData{advertising_data: <<2, 1, 6, 11, 9, 101, 108, 105, 97, 115, 45, 102, 57, 48, 49, 17, 6, 192, 108, 209, 109, 104, 9, 223, 168, 92, 77, 12, 3, 189, 26, 163, 66>>, ocf: 8, ogf: 8, opcode: "\b "}}}
```

**Comment by ConnorRigby** [comment]
oh as it turns out, this **is** an ArgumentError. the max length of this data is `0x1F`. I've tried to pass it something longer than that
